In [3]:
import torch

#现在有batch size 2，每张图片8个query
#比如数据集有9种类别 现在+1 no obj
# 类别从1开始   1 2 3 4 5 6 7 8 9
num_classes = 10
target_classes = torch.full([2,8], num_classes, dtype=torch.int64)

target_classes

tensor([[10, 10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10, 10]])

In [4]:
target_classes.size()

torch.Size([2, 8])

In [6]:
target_classes[0][1] = 1
target_classes[0][6] = 7
target_classes[1][3] = 6
target_classes

tensor([[10,  1, 10, 10, 10, 10,  7, 10],
        [10, 10, 10,  6, 10, 10, 10, 10]])

In [8]:
target_classes_onehot = torch.zeros([2, 8, num_classes+1], dtype=torch.int64)
target_classes_onehot

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [9]:
target_classes_onehot.scatter_(2, target_classes.unsqueeze(-1), 1)
target_classes_onehot

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]])

In [10]:
target_classes_onehot = target_classes_onehot[:,:,:-1]
target_classes_onehot

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [2]:
#分离sub和obj的box
import json
from collections import defaultdict


rel = "/home/minghach/Data/CMH/RelTR/data/vg/rel.json"
val = "/home/minghach/Data/CMH/RelTR/data/vg/val.json"

with open(val, 'r') as val_json:
    val_data = json.load(val_json)

print(type(val_data))
print(val_data.keys())


with open(rel, 'r') as rel_json:
    rel_data = json.load(rel_json)

sub_annotations = {"images": val_data["images"], "categories": val_data["categories"], "annotations": []}
obj_annotations = {"images": val_data["images"], "categories": val_data["categories"], "annotations": []}


val_annotations = defaultdict(list)

for ann in val_data["annotations"]:
    image_id = ann["image_id"]
    # print(image_id)
    val_annotations[image_id].append(ann)
    # assert(0)

sub_id = 1
obj_id = 1
for image_id, rels in rel_data['val'].items():
    image_id = int(image_id)
    if image_id in val_annotations:
        used_sub_boxes = set()
        used_obj_boxes = set()
        for rel in rels:
            sub_idx, obj_idx, _ = rel
            if sub_idx not in used_sub_boxes:
                sub_ann = val_annotations[image_id][sub_idx]
                sub_ann = sub_ann.copy()
                sub_ann["id"] = sub_id
                sub_annotations["annotations"].append(sub_ann)
                used_sub_boxes.add(sub_idx)
                sub_id += 1

            if obj_idx not in used_obj_boxes:
                obj_ann = val_annotations[image_id][obj_idx]
                obj_ann = obj_ann.copy()
                obj_ann["id"] = obj_id
                obj_annotations["annotations"].append(obj_ann)
                used_obj_boxes.add(obj_idx)
                obj_id += 1

# Save the new annotations to JSON files
with open("./sub_val.json", "w") as file:
    json.dump(sub_annotations, file)

with open("./obj_val.json", "w") as file:
    json.dump(obj_annotations, file)

<class 'dict'>
dict_keys(['images', 'annotations', 'categories'])


In [ ]:
test = "/home/minghach/Data/CMH/RelTR/data/vg/test.json"

with open(test, 'r') as test_json:
    test_data = json.load(test_json)

test_annotations = defaultdict(list)
sub_annotations_test = {"images": test_data["images"], "categories": test_data["categories"], "annotations": []}
obj_annotations_test = {"images": test_data["images"], "categories": test_data["categories"], "annotations": []}

for ann in test_data["annotations"]:
    image_id = ann["image_id"]
    test_annotations[image_id].append(ann)

# Process relationships and extract corresponding annotations
sub_id = 1
obj_id = 1
for image_id, rels in rel_data['test'].items():
    image_id = int(image_id)
    if image_id in test_annotations:
        used_sub_boxes = set()
        used_obj_boxes = set()
        for rel in rels:
            sub_idx, obj_idx, _ = rel
            if sub_idx not in used_sub_boxes:
                sub_ann = test_annotations[image_id][sub_idx]
                sub_ann = sub_ann.copy()
                sub_ann["id"] = sub_id
                sub_annotations_test["annotations"].append(sub_ann)
                used_sub_boxes.add(sub_idx)
                sub_id += 1

            if obj_idx not in used_obj_boxes:
                obj_ann = test_annotations[image_id][obj_idx]
                obj_ann = obj_ann.copy()
                obj_ann["id"] = obj_id
                obj_annotations_test["annotations"].append(obj_ann)
                used_obj_boxes.add(obj_idx)
                obj_id += 1


# Save the new JSON files
with open('./sub_test.json', 'w') as file:
    json.dump(sub_annotations_test, file)

with open('./obj_test.json', 'w') as file:
    json.dump(obj_annotations_test, file)

统计Visual genome

统计Train valid Test里面物体的数量和类别分布
统计Relation 主语物体数量和类别分布      宾语物体数量和类别分布

In [16]:
import json
from collections import Counter

rel = "/home/minghach/Data/CMH/RelTR/data/vg/rel.json"
train = "/home/minghach/Data/CMH/RelTR/data/vg/train.json"
val = "/home/minghach/Data/CMH/RelTR/data/vg/val.json"
test = "/home/minghach/Data/CMH/RelTR/data/vg/test.json"

with open(train, 'r') as train_json:
    train_data = json.load(train_json)

with open(val, 'r') as val_json:
    val_data = json.load(val_json)

with open(test, 'r') as test_json:
    test_data = json.load(test_json)

with open(rel, 'r') as rel_json:
    rel_data = json.load(rel_json)


print(val_data.keys())
print(rel_data.keys())
print(rel_data['val'])



dict_keys(['images', 'annotations', 'categories'])
dict_keys(['train', 'val', 'test', 'rel_categories'])
{'1': [[0, 1, 29], [0, 3, 29], [1, 3, 29], [2, 5, 50], [6, 10, 20], [6, 10, 48], [6, 12, 20], [6, 15, 20], [6, 15, 48], [7, 13, 20], [7, 13, 22], [7, 13, 48], [7, 14, 48], [7, 14, 49], [7, 19, 20], [7, 19, 48], [7, 21, 49], [8, 2, 31], [9, 3, 35], [13, 7, 31], [17, 1, 31], [17, 1, 35], [18, 1, 35], [22, 0, 29], [22, 7, 8]], '2': [[1, 5, 20], [1, 10, 20], [1, 11, 20], [1, 13, 20], [1, 14, 20], [15, 6, 29]], '3': [[1, 3, 20], [1, 3, 50], [2, 0, 31], [7, 5, 20]], '4': [[4, 2, 29]], '5': [[2, 1, 31], [3, 6, 29]], '6': [[1, 0, 3], [1, 0, 29], [1, 7, 20], [1, 10, 20], [2, 8, 20], [4, 0, 31], [5, 0, 31], [6, 0, 31], [6, 9, 30], [9, 6, 22], [10, 0, 43], [11, 0, 31], [12, 0, 31], [13, 3, 31]], '7': [[1, 6, 40], [1, 9, 48], [5, 4, 1], [10, 4, 31], [12, 11, 50]], '8': [[1, 3, 20], [1, 3, 49], [1, 9, 48], [1, 15, 20], [2, 8, 30], [7, 0, 30], [8, 11, 31], [12, 4, 31], [13, 11, 31], [16, 12, 31],

In [26]:
from tqdm.notebook import tqdm

def count_categories(data):
    category_counts = Counter()
    for annotation in data['annotations']:
        category_id = annotation['category_id']
        category_counts[f"class_{category_id}"] += 1
    return category_counts


def count_relation_categories(rel_data):
    relation_counts = Counter()
    for dataset in ['train', 'val', 'test']:
        for _, relations in rel_data[dataset].items():
            for rel in relations:
                relation_id = rel[2]
                relation_counts[f"rel_class_{relation_id}"] += 1
    return relation_counts


def count_subject_object_categories(data, rel_data):
    subject_counts = Counter()
    object_counts = Counter()
    for dataset in ['train', 'val', 'test']:
        for image_id, relations in tqdm(rel_data[dataset].items()):
            annotations = {ann['id']: ann for ann in data[dataset]['annotations']}
            for rel in relations:
                sub_id, obj_id = rel[:2]
                sub_cat_id = annotations[sub_id]['category_id']
                obj_cat_id = annotations[obj_id]['category_id']
                subject_counts[f"class_{sub_cat_id}"] += 1
                object_counts[f"class_{obj_cat_id}"] += 1
    return subject_counts, object_counts




In [20]:
train_counts = count_categories(train_data)
print("train Set Categories Distribution:", train_counts)

val_counts = count_categories(val_data)
print("Validation Set Categories Distribution:", val_counts)

test_counts = count_categories(test_data)
print("Test Set Categories Distribution:", test_counts)

train Set Categories Distribution: Counter({'class_78': 33535, 'class_136': 28976, 'class_145': 21705, 'class_111': 21672, 'class_91': 20966, 'class_22': 17118, 'class_149': 15372, 'class_115': 13679, 'class_74': 13112, 'class_61': 13055, 'class_99': 12666, 'class_57': 11126, 'class_58': 10798, 'class_126': 10640, 'class_26': 9187, 'class_76': 8188, 'class_90': 8147, 'class_87': 8095, 'class_112': 7743, 'class_40': 7611, 'class_38': 7567, 'class_45': 7399, 'class_73': 7286, 'class_28': 6720, 'class_54': 6658, 'class_66': 6505, 'class_97': 6437, 'class_124': 6081, 'class_3': 5874, 'class_144': 5620, 'class_121': 5598, 'class_127': 5578, 'class_44': 5421, 'class_60': 5331, 'class_114': 5267, 'class_113': 5018, 'class_104': 4533, 'class_4': 4491, 'class_48': 4453, 'class_59': 4390, 'class_20': 4375, 'class_134': 4284, 'class_105': 3938, 'class_62': 3855, 'class_139': 3828, 'class_135': 3765, 'class_84': 3762, 'class_53': 3752, 'class_21': 3612, 'class_100': 3597, 'class_17': 3580, 'class_

In [22]:
# 统计关系类别的分布
relation_counts = count_relation_categories(rel_data)
print("Relation Categories Distribution:", relation_counts)

Relation Categories Distribution: Counter({'rel_class_31': 152790, 'rel_class_20': 74711, 'rel_class_48': 53128, 'rel_class_30': 45148, 'rel_class_22': 29672, 'rel_class_29': 26440, 'rel_class_50': 16336, 'rel_class_8': 16216, 'rel_class_21': 11902, 'rel_class_1': 8937, 'rel_class_49': 6292, 'rel_class_40': 6199, 'rel_class_43': 5739, 'rel_class_23': 5107, 'rel_class_38': 4434, 'rel_class_41': 3404, 'rel_class_6': 2321, 'rel_class_7': 2292, 'rel_class_46': 1998, 'rel_class_11': 1969, 'rel_class_33': 1784, 'rel_class_16': 1368, 'rel_class_9': 1352, 'rel_class_25': 1244, 'rel_class_47': 1162, 'rel_class_19': 1132, 'rel_class_35': 1006, 'rel_class_24': 916, 'rel_class_5': 874, 'rel_class_14': 750, 'rel_class_13': 733, 'rel_class_10': 727, 'rel_class_44': 678, 'rel_class_4': 657, 'rel_class_12': 615, 'rel_class_36': 552, 'rel_class_32': 497, 'rel_class_42': 493, 'rel_class_26': 448, 'rel_class_28': 421, 'rel_class_45': 369, 'rel_class_2': 338, 'rel_class_17': 293, 'rel_class_3': 287, 'rel_

In [27]:
# 统计主语和宾语的类别分布
subject_counts, object_counts = count_subject_object_categories({'train': train_data, 'val': val_data, 'test': test_data}, rel_data)
print("Subject Categories Distribution:", subject_counts)
print("Object Categories Distribution:", object_counts)


ImportError: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html