In [3]:
import torch

#现在有batch size 2，每张图片8个query
#比如数据集有9种类别 现在+1 no obj
# 类别从1开始   1 2 3 4 5 6 7 8 9
num_classes = 10
target_classes = torch.full([2,8], num_classes, dtype=torch.int64)

target_classes

tensor([[10, 10, 10, 10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10, 10, 10, 10]])

In [4]:
target_classes.size()

torch.Size([2, 8])

In [6]:
target_classes[0][1] = 1
target_classes[0][6] = 7
target_classes[1][3] = 6
target_classes

tensor([[10,  1, 10, 10, 10, 10,  7, 10],
        [10, 10, 10,  6, 10, 10, 10, 10]])

In [8]:
target_classes_onehot = torch.zeros([2, 8, num_classes+1], dtype=torch.int64)
target_classes_onehot

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [9]:
target_classes_onehot.scatter_(2, target_classes.unsqueeze(-1), 1)
target_classes_onehot

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]]])

In [10]:
target_classes_onehot = target_classes_onehot[:,:,:-1]
target_classes_onehot

tensor([[[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]])

In [3]:
#
import json
from collections import defaultdict
# 路径到 rel.json 和 val.json 文件
path_to_rel_json = "/home/cmh/cmh/projects/detrs/RelTR/data/vg/rel.json"
path_to_val_json = "/home/cmh/cmh/projects/detrs/RelTR/data/vg/test.json"

# 加载 rel.json 文件
with open(path_to_rel_json) as f:
    rel_data = json.load(f)

# 加载 val.json 文件
with open(path_to_val_json) as f:
    val_data = json.load(f)

# 提取 val 中的图像和对象信息
# val_images = {img["id"]: img for img in val_data["images"]}
# val_annotations = {}
# for ann in val_data["annotations"]:
#     image_id = ann["image_id"]
#     if image_id not in val_annotations.keys():
#         val_annotations[image_id] = []
#     val_annotations[image_id].append(ann)

val_annotations = defaultdict(list)
# for ann in val_data["annotations"]:
#     image_id = ann["image_id"]
#     if image_id not in val_annotations:
#         val_annotations[image_id] = []
#     val_annotations[image_id].append(ann)

for ann in val_data["annotations"]:
    val_annotations[ann["image_id"]].append(ann)

val_annotations[1]
# 检查 rel.json 中的三元组是否有主语和宾语类别相同的情况
same_category_pairs = []
rel_len_sum = 0
for img_id, triplets in rel_data["test"].items():
    # print(f'img_id {img_id}')
    # print(len(val_annotations[int(img_id)]))

    temp_len = len(triplets)
    rel_len_sum += temp_len  
    for triplet in triplets:
        subj_id, obj_id, _ = triplet
        subj_category = val_annotations[int(img_id)][subj_id]
        obj_category = val_annotations[int(img_id)][obj_id]

        if subj_category == obj_category:
            same_category_pairs.append((img_id, subj_id, obj_id, subj_category))

# 输出结果
num_same_category_pairs = len(same_category_pairs)
# same_category_pairs[:5], num_same_category_pairs  # 显示前5个结果和总数
num_same_category_pairs

print(f'test里面总共有{rel_len_sum}关系')
print(f'主语宾语class一样的关系{num_same_category_pairs}')

test里面总共有152226关系
主语宾语class一样的关系0


这里寻找合适的mask

In [7]:
import torch

num_queries = 5
single_pad = 3
scalar = 2
pad_size = single_pad * scalar

tgt_size = pad_size + num_queries 

attn_mask = torch.ones(tgt_size, tgt_size).to('cuda') < 0   # [390,390]
# match query cannot see the reconstruct
attn_mask[pad_size:, :pad_size] = True        #300行90列的长方形设置为True, 目的是让300个query和90个dn query attn_mask为True
# reconstruct cannot see each other
for i in range(scalar):
    if i == 0:
        # attn_mask[0:18, 18:90]
        attn_mask[single_pad * i:single_pad * (i + 1), single_pad * (i + 1):pad_size] = True
    if i == scalar - 1:
        # attn_mask[18*4:18*5, 0:18]
        attn_mask[single_pad * i:single_pad * (i + 1), :single_pad * i] = True
    else:
        attn_mask[single_pad * i:single_pad * (i + 1), single_pad * (i + 1):pad_size] = True
        attn_mask[single_pad * i:single_pad * (i + 1), :single_pad * i] = True

attn_mask.size()
attn_mask = attn_mask.long()
attn_mask

tensor([[0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0]], device='cuda:0')

In [58]:
def create_attn_mask(num_subject_queries, num_object_queries, num_denoising_groups, single_pad):
    total_queries = num_subject_queries + num_object_queries  # Total number of queries for both subject and object
    pad_size = num_denoising_groups * single_pad # Total denoising queries for each of subject and object
    mask_size = total_queries + pad_size * 2  # Total size of the mask, including both subject and object denoising groups

    # Initialize mask to False (allowing attention interaction)
    attn_mask = torch.zeros((mask_size, mask_size), dtype=torch.bool)

    # Subject matching query not interacting with own and object's denoising group
    attn_mask[pad_size : (pad_size + num_subject_queries), : pad_size] = True 
    attn_mask[pad_size : (pad_size + num_subject_queries), (num_subject_queries + pad_size) : (num_subject_queries+ pad_size + pad_size)] = True 

    # Object matching query not interacting with subject's and own denoising group
    attn_mask[(num_subject_queries + 2*pad_size) : mask_size, : pad_size] = True
    attn_mask[(num_subject_queries + 2*pad_size) : mask_size, (num_subject_queries + pad_size) : (num_subject_queries+ pad_size + pad_size)] = True

    # Denoising group interactions
    for i in range(num_denoising_groups):
        if i == 0:
            # attn_mask[0:18, 18:90]
            attn_mask[single_pad * i:single_pad * (i + 1), single_pad * (i + 1):pad_size] = True
            attn_mask[single_pad * i:single_pad * (i + 1), (pad_size + num_subject_queries + single_pad * (i + 1)) : (num_subject_queries + 2*pad_size)] = True
            attn_mask[(pad_size + num_subject_queries):(pad_size + num_subject_queries + single_pad * (i + 1)), single_pad * (i + 1):pad_size] = True
            attn_mask[(pad_size + num_subject_queries):(pad_size + num_subject_queries + single_pad * (i + 1)), (pad_size + num_subject_queries + single_pad * (i + 1)) : (num_subject_queries + 2*pad_size)] = True
        if i == num_denoising_groups - 1:
            # attn_mask[18*4:18*5, 0:18]
            attn_mask[single_pad * i:single_pad * (i + 1), :single_pad * i] = True
            #行不变，列变
            attn_mask[single_pad * i:single_pad * (i + 1), (pad_size + num_subject_queries):(pad_size + num_subject_queries+ single_pad * i)] = True
            #行变，列不变
            attn_mask[(pad_size + num_subject_queries + single_pad * i):(pad_size + num_subject_queries + single_pad * i)+single_pad, :single_pad * i] = True
            #行变，列变
            attn_mask[(pad_size + num_subject_queries + single_pad * i):(pad_size + num_subject_queries + single_pad * i)+single_pad, (pad_size + num_subject_queries):(pad_size + num_subject_queries+ single_pad * i)] = True

        else:
            attn_mask[single_pad * i:single_pad * (i + 1), single_pad * (i + 1):pad_size] = True
            attn_mask[single_pad * i:single_pad * (i + 1), :single_pad * i] = True

            #行不变，列变
            attn_mask[single_pad * i:single_pad * (i + 1), (pad_size + num_subject_queries + single_pad * (i + 1)) : (2*pad_size + num_subject_queries)] = True
            attn_mask[single_pad * i:single_pad * (i + 1), (pad_size + num_subject_queries) : (pad_size + num_subject_queries + single_pad * i)] = True

            #行变，列不变
            attn_mask[pad_size + num_subject_queries+single_pad * i:pad_size + num_subject_queries+single_pad * (i + 1), single_pad * (i + 1):pad_size] = True
            attn_mask[pad_size + num_subject_queries+single_pad * i:pad_size + num_subject_queries+single_pad * (i + 1), :single_pad * i] = True

            #行变，列变
            attn_mask[pad_size + num_subject_queries+single_pad * i:pad_size + num_subject_queries+single_pad * (i + 1), (pad_size + num_subject_queries + single_pad * (i + 1)) : (2*pad_size + num_subject_queries)] = True
            attn_mask[pad_size + num_subject_queries+single_pad * i:pad_size + num_subject_queries+single_pad * (i + 1), (pad_size + num_subject_queries) : (pad_size + num_subject_queries + single_pad * i)] = True
            
    return attn_mask

attn_mask2 = create_attn_mask(3, 3, single_pad=2, num_denoising_groups=3)
print(attn_mask2.size())
attn_mask2.long()

torch.Size([18, 18])


tensor([[0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
        [1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
        [0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0],
        [1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
        [1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0],
        [1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1